# Generated by Django 6.0.5 on 2026-05-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('result_type', models.CharField(choices=[('change_detection', 'Change Detection'), ('overview_statistics', 'Overview Statistics'), ('transition_matrix', 'Transition Matrix')], max_length=50)),
                ('data', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
