# Generated by Django 6.0.5 on 2026-05-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorlayer',
            name='layer_type',
            field=models.CharField(choices=[('boundary', 'Boundary'), ('hydrology', 'Hydrology')], default='boundary', max_length=20),
        ),
    ]
